### ISSUE TITLE
macos usage + git pull?

### ISSUE THREAD

**Issue by AlJohri** [defclass/git-auto#10]
What is the expected usage on macOS? Manually running the `git-auto` script on each boot? LaunchAgent?

Also, is it within the purview of this script to also `pull` the latest changes too?

I'm considering using this for iOS Sync via Working Copy.

**Comment by defclass** [comment]
Hi @AlJohri,  very nice point.

> Manually running the git-auto script on each boot? LaunchAgent?

I use crontab currently, maybe you can consider it.

e.g.:

```
*/1 * * * * /bin/bash /Directory/to/git-auto -p -o -d  /Directory/to/note/  >> /tmp/sync-note.log 2>&1
```

> Also, is it within the purview of this script to also pull the latest changes too?

this script is mainly used to backup files. It does not support syncing files as it can't solve conflicts.

**Comment by defclass** [comment]
Hi, I am happy to update:

This awesome PR which have been merged into master has supported `git pull --rebase` if you add an optional parameter `-r`.

**Comment by AlJohri** [comment]
@defclass awesome, thank you!
